eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service

zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceid: INDEX-CODES-SERVICE
    api-b:
      path: /api-backtest/**
      serviceid: TRADING-BACKTEST-SERVICE  
    api-c:
      path: /api-view/**
      serviceid: TREND-TRADING-BACKTEST-VIEW
    